### ISSUE TITLE
error trying `resolve` on test inputs

### ISSUE THREAD

**Issue by andrewkern** [grahamgower/demes-c#19]
Hey @grahamgower! trying to figure out if I can implement this library in my `discoal` program. 

I built the library and was trying to see what the `resolve` output would look like but immediately started getting errors using inputs in the `tests/input/valid/` dir.

For instance:

```
./resolve tests/input/valid/admixture_26.yaml
line 15: unknown key: "source"
failed while loading tests/input/valid/admixture_26.yaml
```

what am I doing wrong here?

thanks!
Andy

**Comment by grahamgower** [comment]
Oh, crap, it looks like I left the old test input files in the repository. These got moved to the demes-spec repo a while back and I suppose I forgot to delete them - they've since been updated when a field got changed in the spec. It should be sufficient to run `make test`, and that uses the test cases from the demes-spec git submodule. I'll fix this ASAP.

It would be great to get discoal supporting Demes! Please let us know of any further issues you have (e.g. interpretation of the spec docs). We've done so many iterations of changes and fixes that there might yet be rough edges lurking.

**Comment by grahamgower** [comment]
Thanks for the report @andrewkern. I've remove the old files. I also added a section to the README.md about running the test suite. Let me know if there are further issues, or if you need changes made to the library to streamline its integration into discoal!
